### ISSUE TITLE
internal/client doesn't take in charge Query Params 

### ISSUE THREAD

**Issue by jycamier** [go-gandi/go-gandi#38]
According to https://api.gandi.net/docs/livedns, the client need to have the possibility to configure Query Params.

**Comment by nlewo** [comment]
@jycamier Could you describe a little bit more your need?

For which API path do need to provide query params?
Is it because of the pagination issue (#19)?

**Comment by jycamier** [comment]
Indeed, my needs are related to pagination. 😺 

For exemple : https://github.com/go-gandi/go-gandi/blob/master/livedns/domainrecord.go#L8.
`GetDomainRecords` return only the first page of 500 records without any possibility to get the other pages.

**Comment by nlewo** [comment]
@jycamier could we then close this issue since it seems to already be addressed by #19 ?

**Comment by jycamier** [comment]
Right
